services:
- postgresql
before_script:
 - psql -U postgres  -f script/0_Database.sql
 - psql -U postgres -d r4c -f script/1_Tables.sql
 - psql -U postgres -d r4c -f script/2_FillTables.sql
 - cd src/crowdments/
 - ls
language: java
jdk:
  - oraclejdk8
script: mvn clean verify -DskipTests=false -DskipITs=false -DskipSTs=false
deploy:
  provider: boxfuse
  user: "4c517afac1b64ac99677c188de9dfcd3"
  secret: "lAW6mnOC5tDFSvorNaz9bZMSAr0RKFFcObn5OGHlheKCidtxH7O63wmegOq72CvD"
  payload: "war"
