services:
- postgresql
before_script:
# - psql -c 'create database tecservice;' -U postgres
 - psql -U postgres  -f  crowdments/script/0_Database.sql
 - psql -U postgres -d crowdments/script/1_Tables.sql
 - cd crowdments/src/crowdments/
 - ls
language: java
jdk:
  - oraclejdk8
script: mvn clean verify -DskipTests=false -DskipITs=false -DskipSTs=false
